
common: &common
  adapter: postgresql
  username: postgres
  password: 180lbs

development:
  <<: *common
  database: idlik12_development

test:
  <<: *common
  database: idlik12_test

production:
  <<: *common
  database: idlik12_production